// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: moviedb_service.proto

package moviedb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastAndCrewType int32

const (
	CastAndCrewType_ACTOR              CastAndCrewType = 0
	CastAndCrewType_DIRECTOR           CastAndCrewType = 1
	CastAndCrewType_PRODUCER           CastAndCrewType = 2
	CastAndCrewType_WRITER             CastAndCrewType = 3
	CastAndCrewType_MUSIC_DIRECTOR     CastAndCrewType = 4
	CastAndCrewType_CINEMATOGRAPHER    CastAndCrewType = 5
	CastAndCrewType_EDITOR             CastAndCrewType = 6
	CastAndCrewType_ART_DIRECTOR       CastAndCrewType = 7
	CastAndCrewType_COSTUME_DESIGNER   CastAndCrewType = 8
	CastAndCrewType_MAKEUP_ARTIST      CastAndCrewType = 9
	CastAndCrewType_SOUND_DESIGNER     CastAndCrewType = 10
	CastAndCrewType_VFX_ARTIST         CastAndCrewType = 11
	CastAndCrewType_STUNT_PERFORMER    CastAndCrewType = 12
	CastAndCrewType_CHOREOGRAPHER      CastAndCrewType = 13
	CastAndCrewType_LYRICIST           CastAndCrewType = 14
	CastAndCrewType_PLAYBACK_SINGER    CastAndCrewType = 15
	CastAndCrewType_DUBBING_ARTIST     CastAndCrewType = 16
	CastAndCrewType_PUBLICITY_DESIGNER CastAndCrewType = 17
	CastAndCrewType_PUBLIC_RELATIONS   CastAndCrewType = 18
	CastAndCrewType_DISTRIBUTOR        CastAndCrewType = 19
	CastAndCrewType_MARKETING          CastAndCrewType = 20
	CastAndCrewType_LEGAL              CastAndCrewType = 21
	CastAndCrewType_FINANCE            CastAndCrewType = 22
	CastAndCrewType_PRODUCTION         CastAndCrewType = 23
	CastAndCrewType_OTHER              CastAndCrewType = 24
)

// Enum value maps for CastAndCrewType.
var (
	CastAndCrewType_name = map[int32]string{
		0:  "ACTOR",
		1:  "DIRECTOR",
		2:  "PRODUCER",
		3:  "WRITER",
		4:  "MUSIC_DIRECTOR",
		5:  "CINEMATOGRAPHER",
		6:  "EDITOR",
		7:  "ART_DIRECTOR",
		8:  "COSTUME_DESIGNER",
		9:  "MAKEUP_ARTIST",
		10: "SOUND_DESIGNER",
		11: "VFX_ARTIST",
		12: "STUNT_PERFORMER",
		13: "CHOREOGRAPHER",
		14: "LYRICIST",
		15: "PLAYBACK_SINGER",
		16: "DUBBING_ARTIST",
		17: "PUBLICITY_DESIGNER",
		18: "PUBLIC_RELATIONS",
		19: "DISTRIBUTOR",
		20: "MARKETING",
		21: "LEGAL",
		22: "FINANCE",
		23: "PRODUCTION",
		24: "OTHER",
	}
	CastAndCrewType_value = map[string]int32{
		"ACTOR":              0,
		"DIRECTOR":           1,
		"PRODUCER":           2,
		"WRITER":             3,
		"MUSIC_DIRECTOR":     4,
		"CINEMATOGRAPHER":    5,
		"EDITOR":             6,
		"ART_DIRECTOR":       7,
		"COSTUME_DESIGNER":   8,
		"MAKEUP_ARTIST":      9,
		"SOUND_DESIGNER":     10,
		"VFX_ARTIST":         11,
		"STUNT_PERFORMER":    12,
		"CHOREOGRAPHER":      13,
		"LYRICIST":           14,
		"PLAYBACK_SINGER":    15,
		"DUBBING_ARTIST":     16,
		"PUBLICITY_DESIGNER": 17,
		"PUBLIC_RELATIONS":   18,
		"DISTRIBUTOR":        19,
		"MARKETING":          20,
		"LEGAL":              21,
		"FINANCE":            22,
		"PRODUCTION":         23,
		"OTHER":              24,
	}
)

func (x CastAndCrewType) Enum() *CastAndCrewType {
	p := new(CastAndCrewType)
	*p = x
	return p
}

func (x CastAndCrewType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastAndCrewType) Descriptor() protoreflect.EnumDescriptor {
	return file_moviedb_service_proto_enumTypes[0].Descriptor()
}

func (CastAndCrewType) Type() protoreflect.EnumType {
	return &file_moviedb_service_proto_enumTypes[0]
}

func (x CastAndCrewType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CastAndCrewType.Descriptor instead.
func (CastAndCrewType) EnumDescriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{0}
}

type VenueType int32

const (
	VenueType_MOVIE   VenueType = 0
	VenueType_CONCERT VenueType = 1
	VenueType_PLAY    VenueType = 2
	VenueType_STANDUP VenueType = 3
)

// Enum value maps for VenueType.
var (
	VenueType_name = map[int32]string{
		0: "MOVIE",
		1: "CONCERT",
		2: "PLAY",
		3: "STANDUP",
	}
	VenueType_value = map[string]int32{
		"MOVIE":   0,
		"CONCERT": 1,
		"PLAY":    2,
		"STANDUP": 3,
	}
)

func (x VenueType) Enum() *VenueType {
	p := new(VenueType)
	*p = x
	return p
}

func (x VenueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VenueType) Descriptor() protoreflect.EnumDescriptor {
	return file_moviedb_service_proto_enumTypes[1].Descriptor()
}

func (VenueType) Type() protoreflect.EnumType {
	return &file_moviedb_service_proto_enumTypes[1]
}

func (x VenueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VenueType.Descriptor instead.
func (VenueType) EnumDescriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{1}
}

type SeatType int32

const (
	SeatType_TWO_D   SeatType = 0
	SeatType_THREE_D SeatType = 1
	SeatType_FOUR_D  SeatType = 2
	SeatType_NORMAL  SeatType = 3
	SeatType_VIP     SeatType = 4
)

// Enum value maps for SeatType.
var (
	SeatType_name = map[int32]string{
		0: "TWO_D",
		1: "THREE_D",
		2: "FOUR_D",
		3: "NORMAL",
		4: "VIP",
	}
	SeatType_value = map[string]int32{
		"TWO_D":   0,
		"THREE_D": 1,
		"FOUR_D":  2,
		"NORMAL":  3,
		"VIP":     4,
	}
)

func (x SeatType) Enum() *SeatType {
	p := new(SeatType)
	*p = x
	return p
}

func (x SeatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeatType) Descriptor() protoreflect.EnumDescriptor {
	return file_moviedb_service_proto_enumTypes[2].Descriptor()
}

func (SeatType) Type() protoreflect.EnumType {
	return &file_moviedb_service_proto_enumTypes[2]
}

func (x SeatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeatType.Descriptor instead.
func (SeatType) EnumDescriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{2}
}

type CastAndCrew struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          CastAndCrewType        `protobuf:"varint,2,opt,name=type,proto3,enum=moviedb_service.CastAndCrewType" json:"type,omitempty"`
	CharacterName string                 `protobuf:"bytes,3,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Photourl      string                 `protobuf:"bytes,4,opt,name=photourl,proto3" json:"photourl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastAndCrew) Reset() {
	*x = CastAndCrew{}
	mi := &file_moviedb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastAndCrew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastAndCrew) ProtoMessage() {}

func (x *CastAndCrew) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastAndCrew.ProtoReflect.Descriptor instead.
func (*CastAndCrew) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{0}
}

func (x *CastAndCrew) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CastAndCrew) GetType() CastAndCrewType {
	if x != nil {
		return x.Type
	}
	return CastAndCrewType_ACTOR
}

func (x *CastAndCrew) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CastAndCrew) GetPhotourl() string {
	if x != nil {
		return x.Photourl
	}
	return ""
}

type MovieTimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	MovieFormat   SeatType               `protobuf:"varint,5,opt,name=movie_format,json=movieFormat,proto3,enum=moviedb_service.SeatType" json:"movie_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieTimeSlot) Reset() {
	*x = MovieTimeSlot{}
	mi := &file_moviedb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieTimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTimeSlot) ProtoMessage() {}

func (x *MovieTimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTimeSlot.ProtoReflect.Descriptor instead.
func (*MovieTimeSlot) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{1}
}

func (x *MovieTimeSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MovieTimeSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *MovieTimeSlot) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MovieTimeSlot) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MovieTimeSlot) GetMovieFormat() SeatType {
	if x != nil {
		return x.MovieFormat
	}
	return SeatType_TWO_D
}

type Movie struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Duration        int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Language        []string               `protobuf:"bytes,4,rep,name=language,proto3" json:"language,omitempty"`
	Type            []string               `protobuf:"bytes,5,rep,name=type,proto3" json:"type,omitempty"`
	CastCrew        []*CastAndCrew         `protobuf:"bytes,6,rep,name=cast_crew,json=castCrew,proto3" json:"cast_crew,omitempty"`
	PosterUrl       string                 `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	TrailerUrl      string                 `protobuf:"bytes,8,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	ReleaseDate     string                 `protobuf:"bytes,9,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	MovieResolution []string               `protobuf:"bytes,10,rep,name=movie_resolution,json=movieResolution,proto3" json:"movie_resolution,omitempty"`
	Venues          []*Venue               `protobuf:"bytes,11,rep,name=venues,proto3" json:"venues,omitempty"`
	Movieid         string                 `protobuf:"bytes,12,opt,name=movieid,proto3" json:"movieid,omitempty"`
	Votes           int64                  `protobuf:"varint,13,opt,name=votes,proto3" json:"votes,omitempty"`
	Ranking         int32                  `protobuf:"varint,14,opt,name=ranking,proto3" json:"ranking,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_moviedb_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{2}
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Movie) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Movie) GetLanguage() []string {
	if x != nil {
		return x.Language
	}
	return nil
}

func (x *Movie) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Movie) GetCastCrew() []*CastAndCrew {
	if x != nil {
		return x.CastCrew
	}
	return nil
}

func (x *Movie) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *Movie) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *Movie) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Movie) GetMovieResolution() []string {
	if x != nil {
		return x.MovieResolution
	}
	return nil
}

func (x *Movie) GetVenues() []*Venue {
	if x != nil {
		return x.Venues
	}
	return nil
}

func (x *Movie) GetMovieid() string {
	if x != nil {
		return x.Movieid
	}
	return ""
}

func (x *Movie) GetVotes() int64 {
	if x != nil {
		return x.Votes
	}
	return 0
}

func (x *Movie) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

type SeatMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatNumber    string                 `protobuf:"bytes,1,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	IsBooked      bool                   `protobuf:"varint,2,opt,name=is_booked,json=isBooked,proto3" json:"is_booked,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Row           int32                  `protobuf:"varint,4,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	Type          SeatType               `protobuf:"varint,6,opt,name=type,proto3,enum=moviedb_service.SeatType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatMatrix) Reset() {
	*x = SeatMatrix{}
	mi := &file_moviedb_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatMatrix) ProtoMessage() {}

func (x *SeatMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatMatrix.ProtoReflect.Descriptor instead.
func (*SeatMatrix) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{3}
}

func (x *SeatMatrix) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *SeatMatrix) GetIsBooked() bool {
	if x != nil {
		return x.IsBooked
	}
	return false
}

func (x *SeatMatrix) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeatMatrix) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *SeatMatrix) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *SeatMatrix) GetType() SeatType {
	if x != nil {
		return x.Type
	}
	return SeatType_TWO_D
}

type Venue struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type                 VenueType              `protobuf:"varint,3,opt,name=type,proto3,enum=moviedb_service.VenueType" json:"type,omitempty"`
	Rows                 int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns              int32                  `protobuf:"varint,5,opt,name=columns,proto3" json:"columns,omitempty"`
	Longitude            float32                `protobuf:"fixed32,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float32                `protobuf:"fixed32,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	ScreenNumber         int32                  `protobuf:"varint,8,opt,name=screen_number,json=screenNumber,proto3" json:"screen_number,omitempty"`
	Seats                []*SeatMatrix          `protobuf:"bytes,9,rep,name=seats,proto3" json:"seats,omitempty"`
	MovieTimeSlots       []*MovieTimeSlot       `protobuf:"bytes,10,rep,name=movie_time_slots,json=movieTimeSlots,proto3" json:"movie_time_slots,omitempty"`
	Movies               []*Movie               `protobuf:"bytes,11,rep,name=movies,proto3" json:"movies,omitempty"`
	Id                   int32                  `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`
	MovieFormatSupported []string               `protobuf:"bytes,13,rep,name=movie_format_supported,json=movieFormatSupported,proto3" json:"movie_format_supported,omitempty"`
	LanguageSupported    []string               `protobuf:"bytes,14,rep,name=language_supported,json=languageSupported,proto3" json:"language_supported,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Venue) Reset() {
	*x = Venue{}
	mi := &file_moviedb_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Venue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Venue) ProtoMessage() {}

func (x *Venue) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Venue.ProtoReflect.Descriptor instead.
func (*Venue) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{4}
}

func (x *Venue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Venue) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Venue) GetType() VenueType {
	if x != nil {
		return x.Type
	}
	return VenueType_MOVIE
}

func (x *Venue) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Venue) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *Venue) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Venue) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Venue) GetScreenNumber() int32 {
	if x != nil {
		return x.ScreenNumber
	}
	return 0
}

func (x *Venue) GetSeats() []*SeatMatrix {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *Venue) GetMovieTimeSlots() []*MovieTimeSlot {
	if x != nil {
		return x.MovieTimeSlots
	}
	return nil
}

func (x *Venue) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *Venue) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Venue) GetMovieFormatSupported() []string {
	if x != nil {
		return x.MovieFormatSupported
	}
	return nil
}

func (x *Venue) GetLanguageSupported() []string {
	if x != nil {
		return x.LanguageSupported
	}
	return nil
}

type MovieList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieList) Reset() {
	*x = MovieList{}
	mi := &file_moviedb_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieList) ProtoMessage() {}

func (x *MovieList) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieList.ProtoReflect.Descriptor instead.
func (*MovieList) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{5}
}

func (x *MovieList) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type MovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Movieid       string                 `protobuf:"bytes,2,opt,name=movieid,proto3" json:"movieid,omitempty"`
	Venueid       string                 `protobuf:"bytes,3,opt,name=venueid,proto3" json:"venueid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieRequest) Reset() {
	*x = MovieRequest{}
	mi := &file_moviedb_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieRequest) ProtoMessage() {}

func (x *MovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieRequest.ProtoReflect.Descriptor instead.
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{6}
}

func (x *MovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieRequest) GetMovieid() string {
	if x != nil {
		return x.Movieid
	}
	return ""
}

func (x *MovieRequest) GetVenueid() string {
	if x != nil {
		return x.Venueid
	}
	return ""
}

type MovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Movie         *Movie                 `protobuf:"bytes,3,opt,name=movie,proto3" json:"movie,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieResponse) Reset() {
	*x = MovieResponse{}
	mi := &file_moviedb_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieResponse) ProtoMessage() {}

func (x *MovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieResponse.ProtoReflect.Descriptor instead.
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{7}
}

func (x *MovieResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MovieResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

func (x *MovieResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MovieListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MovieList     *MovieList             `protobuf:"bytes,3,opt,name=movie_list,json=movieList,proto3" json:"movie_list,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieListResponse) Reset() {
	*x = MovieListResponse{}
	mi := &file_moviedb_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieListResponse) ProtoMessage() {}

func (x *MovieListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieListResponse.ProtoReflect.Descriptor instead.
func (*MovieListResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{8}
}

func (x *MovieListResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MovieListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MovieListResponse) GetMovieList() *MovieList {
	if x != nil {
		return x.MovieList
	}
	return nil
}

func (x *MovieListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Venue         *Venue                 `protobuf:"bytes,3,opt,name=Venue,proto3" json:"Venue,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VenueResponse) Reset() {
	*x = VenueResponse{}
	mi := &file_moviedb_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueResponse) ProtoMessage() {}

func (x *VenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueResponse.ProtoReflect.Descriptor instead.
func (*VenueResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{9}
}

func (x *VenueResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VenueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VenueResponse) GetVenue() *Venue {
	if x != nil {
		return x.Venue
	}
	return nil
}

func (x *VenueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUpcomingMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingMovieRequest) Reset() {
	*x = GetUpcomingMovieRequest{}
	mi := &file_moviedb_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingMovieRequest) ProtoMessage() {}

func (x *GetUpcomingMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingMovieRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingMovieRequest) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUpcomingMovieRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetUpcomingMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MovieList     []*Movie               `protobuf:"bytes,3,rep,name=movie_list,json=movieList,proto3" json:"movie_list,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingMovieResponse) Reset() {
	*x = GetUpcomingMovieResponse{}
	mi := &file_moviedb_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingMovieResponse) ProtoMessage() {}

func (x *GetUpcomingMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviedb_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingMovieResponse.ProtoReflect.Descriptor instead.
func (*GetUpcomingMovieResponse) Descriptor() ([]byte, []int) {
	return file_moviedb_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetUpcomingMovieResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUpcomingMovieResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUpcomingMovieResponse) GetMovieList() []*Movie {
	if x != nil {
		return x.MovieList
	}
	return nil
}

func (x *GetUpcomingMovieResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_moviedb_service_proto protoreflect.FileDescriptor

const file_moviedb_service_proto_rawDesc = "" +
	"\n" +
	"\x15moviedb_service.proto\x12\x0fmoviedb_service\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x01\n" +
	"\vCastAndCrew\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .moviedb_service.CastAndCrewTypeR\x04type\x12%\n" +
	"\x0echaracter_name\x18\x03 \x01(\tR\rcharacterName\x12\x1a\n" +
	"\bphotourl\x18\x04 \x01(\tR\bphotourl\"\xb7\x01\n" +
	"\rMovieTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12<\n" +
	"\fmovie_format\x18\x05 \x01(\x0e2\x19.moviedb_service.SeatTypeR\vmovieFormat\"\xce\x03\n" +
	"\x05Movie\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x1a\n" +
	"\blanguage\x18\x04 \x03(\tR\blanguage\x12\x12\n" +
	"\x04type\x18\x05 \x03(\tR\x04type\x129\n" +
	"\tcast_crew\x18\x06 \x03(\v2\x1c.moviedb_service.CastAndCrewR\bcastCrew\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\x12\x1f\n" +
	"\vtrailer_url\x18\b \x01(\tR\n" +
	"trailerUrl\x12!\n" +
	"\frelease_date\x18\t \x01(\tR\vreleaseDate\x12)\n" +
	"\x10movie_resolution\x18\n" +
	" \x03(\tR\x0fmovieResolution\x12.\n" +
	"\x06venues\x18\v \x03(\v2\x16.moviedb_service.VenueR\x06venues\x12\x18\n" +
	"\amovieid\x18\f \x01(\tR\amovieid\x12\x14\n" +
	"\x05votes\x18\r \x01(\x03R\x05votes\x12\x18\n" +
	"\aranking\x18\x0e \x01(\x05R\aranking\"\xb9\x01\n" +
	"\n" +
	"SeatMatrix\x12\x1f\n" +
	"\vseat_number\x18\x01 \x01(\tR\n" +
	"seatNumber\x12\x1b\n" +
	"\tis_booked\x18\x02 \x01(\bR\bisBooked\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x10\n" +
	"\x03row\x18\x04 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12-\n" +
	"\x04type\x18\x06 \x01(\x0e2\x19.moviedb_service.SeatTypeR\x04type\"\x94\x04\n" +
	"\x05Venue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.moviedb_service.VenueTypeR\x04type\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x12\x18\n" +
	"\acolumns\x18\x05 \x01(\x05R\acolumns\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x02R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x02R\blatitude\x12#\n" +
	"\rscreen_number\x18\b \x01(\x05R\fscreenNumber\x121\n" +
	"\x05seats\x18\t \x03(\v2\x1b.moviedb_service.SeatMatrixR\x05seats\x12H\n" +
	"\x10movie_time_slots\x18\n" +
	" \x03(\v2\x1e.moviedb_service.MovieTimeSlotR\x0emovieTimeSlots\x12.\n" +
	"\x06movies\x18\v \x03(\v2\x16.moviedb_service.MovieR\x06movies\x12\x0e\n" +
	"\x02id\x18\f \x01(\x05R\x02id\x124\n" +
	"\x16movie_format_supported\x18\r \x03(\tR\x14movieFormatSupported\x12-\n" +
	"\x12language_supported\x18\x0e \x03(\tR\x11languageSupported\";\n" +
	"\tMovieList\x12.\n" +
	"\x06movies\x18\x01 \x03(\v2\x16.moviedb_service.MovieR\x06movies\"X\n" +
	"\fMovieRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amovieid\x18\x02 \x01(\tR\amovieid\x12\x18\n" +
	"\avenueid\x18\x03 \x01(\tR\avenueid\"\x85\x01\n" +
	"\rMovieResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x05movie\x18\x03 \x01(\v2\x16.moviedb_service.MovieR\x05movie\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x96\x01\n" +
	"\x11MovieListResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"movie_list\x18\x03 \x01(\v2\x1a.moviedb_service.MovieListR\tmovieList\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x85\x01\n" +
	"\rVenueResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x05Venue\x18\x03 \x01(\v2\x16.moviedb_service.VenueR\x05Venue\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"-\n" +
	"\x17GetUpcomingMovieRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"\x99\x01\n" +
	"\x18GetUpcomingMovieResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\n" +
	"movie_list\x18\x03 \x03(\v2\x16.moviedb_service.MovieR\tmovieList\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\xb8\x03\n" +
	"\x0fCastAndCrewType\x12\t\n" +
	"\x05ACTOR\x10\x00\x12\f\n" +
	"\bDIRECTOR\x10\x01\x12\f\n" +
	"\bPRODUCER\x10\x02\x12\n" +
	"\n" +
	"\x06WRITER\x10\x03\x12\x12\n" +
	"\x0eMUSIC_DIRECTOR\x10\x04\x12\x13\n" +
	"\x0fCINEMATOGRAPHER\x10\x05\x12\n" +
	"\n" +
	"\x06EDITOR\x10\x06\x12\x10\n" +
	"\fART_DIRECTOR\x10\a\x12\x14\n" +
	"\x10COSTUME_DESIGNER\x10\b\x12\x11\n" +
	"\rMAKEUP_ARTIST\x10\t\x12\x12\n" +
	"\x0eSOUND_DESIGNER\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"VFX_ARTIST\x10\v\x12\x13\n" +
	"\x0fSTUNT_PERFORMER\x10\f\x12\x11\n" +
	"\rCHOREOGRAPHER\x10\r\x12\f\n" +
	"\bLYRICIST\x10\x0e\x12\x13\n" +
	"\x0fPLAYBACK_SINGER\x10\x0f\x12\x12\n" +
	"\x0eDUBBING_ARTIST\x10\x10\x12\x16\n" +
	"\x12PUBLICITY_DESIGNER\x10\x11\x12\x14\n" +
	"\x10PUBLIC_RELATIONS\x10\x12\x12\x0f\n" +
	"\vDISTRIBUTOR\x10\x13\x12\r\n" +
	"\tMARKETING\x10\x14\x12\t\n" +
	"\x05LEGAL\x10\x15\x12\v\n" +
	"\aFINANCE\x10\x16\x12\x0e\n" +
	"\n" +
	"PRODUCTION\x10\x17\x12\t\n" +
	"\x05OTHER\x10\x18*:\n" +
	"\tVenueType\x12\t\n" +
	"\x05MOVIE\x10\x00\x12\v\n" +
	"\aCONCERT\x10\x01\x12\b\n" +
	"\x04PLAY\x10\x02\x12\v\n" +
	"\aSTANDUP\x10\x03*C\n" +
	"\bSeatType\x12\t\n" +
	"\x05TWO_D\x10\x00\x12\v\n" +
	"\aTHREE_D\x10\x01\x12\n" +
	"\n" +
	"\x06FOUR_D\x10\x02\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x03\x12\a\n" +
	"\x03VIP\x10\x042\xc6\a\n" +
	"\x0eMovieDBService\x12B\n" +
	"\bAddMovie\x12\x16.moviedb_service.Movie\x1a\x1e.moviedb_service.MovieResponse\x12I\n" +
	"\bGetMovie\x12\x1d.moviedb_service.MovieRequest\x1a\x1e.moviedb_service.MovieResponse\x12J\n" +
	"\fGetAllMovies\x12\x16.google.protobuf.Empty\x1a\".moviedb_service.MovieListResponse\x12E\n" +
	"\vUpdateMovie\x12\x16.moviedb_service.Movie\x1a\x1e.moviedb_service.MovieResponse\x12L\n" +
	"\vDeleteMovie\x12\x1d.moviedb_service.MovieRequest\x1a\x1e.moviedb_service.MovieResponse\x12B\n" +
	"\bAddVenue\x12\x16.moviedb_service.Venue\x1a\x1e.moviedb_service.VenueResponse\x12I\n" +
	"\bGetVenue\x12\x1d.moviedb_service.MovieRequest\x1a\x1e.moviedb_service.VenueResponse\x12J\n" +
	"\fGetAllVenues\x12\x16.google.protobuf.Empty\x1a\".moviedb_service.MovieListResponse\x12E\n" +
	"\vUpdateVenue\x12\x16.moviedb_service.Venue\x1a\x1e.moviedb_service.VenueResponse\x12L\n" +
	"\vDeleteVenue\x12\x1d.moviedb_service.MovieRequest\x1a\x1e.moviedb_service.MovieResponse\x12h\n" +
	"\x11GetUpcomingMovies\x12(.moviedb_service.GetUpcomingMovieRequest\x1a).moviedb_service.GetUpcomingMovieResponse\x12j\n" +
	"\x13GetNowPlayingMovies\x12(.moviedb_service.GetUpcomingMovieRequest\x1a).moviedb_service.GetUpcomingMovieResponseBFZDgithub.com/kartik7120/booking_moviedb_service/cmd/grpcServer;moviedbb\x06proto3"

var (
	file_moviedb_service_proto_rawDescOnce sync.Once
	file_moviedb_service_proto_rawDescData []byte
)

func file_moviedb_service_proto_rawDescGZIP() []byte {
	file_moviedb_service_proto_rawDescOnce.Do(func() {
		file_moviedb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moviedb_service_proto_rawDesc), len(file_moviedb_service_proto_rawDesc)))
	})
	return file_moviedb_service_proto_rawDescData
}

var file_moviedb_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_moviedb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_moviedb_service_proto_goTypes = []any{
	(CastAndCrewType)(0),             // 0: moviedb_service.CastAndCrewType
	(VenueType)(0),                   // 1: moviedb_service.VenueType
	(SeatType)(0),                    // 2: moviedb_service.SeatType
	(*CastAndCrew)(nil),              // 3: moviedb_service.CastAndCrew
	(*MovieTimeSlot)(nil),            // 4: moviedb_service.MovieTimeSlot
	(*Movie)(nil),                    // 5: moviedb_service.Movie
	(*SeatMatrix)(nil),               // 6: moviedb_service.SeatMatrix
	(*Venue)(nil),                    // 7: moviedb_service.Venue
	(*MovieList)(nil),                // 8: moviedb_service.MovieList
	(*MovieRequest)(nil),             // 9: moviedb_service.MovieRequest
	(*MovieResponse)(nil),            // 10: moviedb_service.MovieResponse
	(*MovieListResponse)(nil),        // 11: moviedb_service.MovieListResponse
	(*VenueResponse)(nil),            // 12: moviedb_service.VenueResponse
	(*GetUpcomingMovieRequest)(nil),  // 13: moviedb_service.GetUpcomingMovieRequest
	(*GetUpcomingMovieResponse)(nil), // 14: moviedb_service.GetUpcomingMovieResponse
	(*empty.Empty)(nil),              // 15: google.protobuf.Empty
}
var file_moviedb_service_proto_depIdxs = []int32{
	0,  // 0: moviedb_service.CastAndCrew.type:type_name -> moviedb_service.CastAndCrewType
	2,  // 1: moviedb_service.MovieTimeSlot.movie_format:type_name -> moviedb_service.SeatType
	3,  // 2: moviedb_service.Movie.cast_crew:type_name -> moviedb_service.CastAndCrew
	7,  // 3: moviedb_service.Movie.venues:type_name -> moviedb_service.Venue
	2,  // 4: moviedb_service.SeatMatrix.type:type_name -> moviedb_service.SeatType
	1,  // 5: moviedb_service.Venue.type:type_name -> moviedb_service.VenueType
	6,  // 6: moviedb_service.Venue.seats:type_name -> moviedb_service.SeatMatrix
	4,  // 7: moviedb_service.Venue.movie_time_slots:type_name -> moviedb_service.MovieTimeSlot
	5,  // 8: moviedb_service.Venue.movies:type_name -> moviedb_service.Movie
	5,  // 9: moviedb_service.MovieList.movies:type_name -> moviedb_service.Movie
	5,  // 10: moviedb_service.MovieResponse.movie:type_name -> moviedb_service.Movie
	8,  // 11: moviedb_service.MovieListResponse.movie_list:type_name -> moviedb_service.MovieList
	7,  // 12: moviedb_service.VenueResponse.Venue:type_name -> moviedb_service.Venue
	5,  // 13: moviedb_service.GetUpcomingMovieResponse.movie_list:type_name -> moviedb_service.Movie
	5,  // 14: moviedb_service.MovieDBService.AddMovie:input_type -> moviedb_service.Movie
	9,  // 15: moviedb_service.MovieDBService.GetMovie:input_type -> moviedb_service.MovieRequest
	15, // 16: moviedb_service.MovieDBService.GetAllMovies:input_type -> google.protobuf.Empty
	5,  // 17: moviedb_service.MovieDBService.UpdateMovie:input_type -> moviedb_service.Movie
	9,  // 18: moviedb_service.MovieDBService.DeleteMovie:input_type -> moviedb_service.MovieRequest
	7,  // 19: moviedb_service.MovieDBService.AddVenue:input_type -> moviedb_service.Venue
	9,  // 20: moviedb_service.MovieDBService.GetVenue:input_type -> moviedb_service.MovieRequest
	15, // 21: moviedb_service.MovieDBService.GetAllVenues:input_type -> google.protobuf.Empty
	7,  // 22: moviedb_service.MovieDBService.UpdateVenue:input_type -> moviedb_service.Venue
	9,  // 23: moviedb_service.MovieDBService.DeleteVenue:input_type -> moviedb_service.MovieRequest
	13, // 24: moviedb_service.MovieDBService.GetUpcomingMovies:input_type -> moviedb_service.GetUpcomingMovieRequest
	13, // 25: moviedb_service.MovieDBService.GetNowPlayingMovies:input_type -> moviedb_service.GetUpcomingMovieRequest
	10, // 26: moviedb_service.MovieDBService.AddMovie:output_type -> moviedb_service.MovieResponse
	10, // 27: moviedb_service.MovieDBService.GetMovie:output_type -> moviedb_service.MovieResponse
	11, // 28: moviedb_service.MovieDBService.GetAllMovies:output_type -> moviedb_service.MovieListResponse
	10, // 29: moviedb_service.MovieDBService.UpdateMovie:output_type -> moviedb_service.MovieResponse
	10, // 30: moviedb_service.MovieDBService.DeleteMovie:output_type -> moviedb_service.MovieResponse
	12, // 31: moviedb_service.MovieDBService.AddVenue:output_type -> moviedb_service.VenueResponse
	12, // 32: moviedb_service.MovieDBService.GetVenue:output_type -> moviedb_service.VenueResponse
	11, // 33: moviedb_service.MovieDBService.GetAllVenues:output_type -> moviedb_service.MovieListResponse
	12, // 34: moviedb_service.MovieDBService.UpdateVenue:output_type -> moviedb_service.VenueResponse
	10, // 35: moviedb_service.MovieDBService.DeleteVenue:output_type -> moviedb_service.MovieResponse
	14, // 36: moviedb_service.MovieDBService.GetUpcomingMovies:output_type -> moviedb_service.GetUpcomingMovieResponse
	14, // 37: moviedb_service.MovieDBService.GetNowPlayingMovies:output_type -> moviedb_service.GetUpcomingMovieResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_moviedb_service_proto_init() }
func file_moviedb_service_proto_init() {
	if File_moviedb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moviedb_service_proto_rawDesc), len(file_moviedb_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moviedb_service_proto_goTypes,
		DependencyIndexes: file_moviedb_service_proto_depIdxs,
		EnumInfos:         file_moviedb_service_proto_enumTypes,
		MessageInfos:      file_moviedb_service_proto_msgTypes,
	}.Build()
	File_moviedb_service_proto = out.File
	file_moviedb_service_proto_goTypes = nil
	file_moviedb_service_proto_depIdxs = nil
}
